# Generated by Django 5.1.15 on 2026-04-26 20:11

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Must run before any HnswIndex creation. Idempotent (CREATE EXTENSION IF NOT EXISTS).
        VectorExtension(),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2048, unique=True)),
                ('scraped_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_status_code', models.IntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['url'],
            },
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255, unique=True)),
                ('scrapable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['host'],
            },
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('Offer', 'Offer'), ('Matching', 'Matching')], default='Offer', max_length=16)),
                ('count', models.PositiveIntegerField(default=0)),
                ('file', models.FileField(blank=True, upload_to='exports/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Unprocessed', 'Unprocessed'), ('Enqueued', 'Enqueued'), ('Importing', 'Importing'), ('Error', 'Error'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Success', 'Success')], default='Unprocessed', max_length=16)),
                ('total', models.PositiveIntegerField(default=0)),
                ('pending', models.PositiveIntegerField(default=0)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('failure_info', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('importer_class_name', models.CharField(default='SchleiperImporter', max_length=255)),
                ('file', models.FileField(upload_to='imports/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255)),
                ('common_sku', models.CharField(blank=True, default='', max_length=255)),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, default='')),
                ('ean', models.CharField(blank=True, default='', max_length=32)),
                ('original_image_url', models.URLField(blank=True, default='', max_length=2048)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('custom_attributes', models.JSONField(blank=True, default=dict)),
                ('public', models.BooleanField(default=False)),
                ('matchings_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('embedding_input_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='core.brand')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='core.channel')),
                ('pages', models.ManyToManyField(blank=True, related_name='offers', to='core.page')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='core.retailer')),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='core.website')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='retailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channels', to='core.retailer'),
        ),
        migrations.AddField(
            model_name='page',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.website'),
        ),
        migrations.AddField(
            model_name='channel',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='channels', to='core.website'),
        ),
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('errored', 'Errored')], default='suggested', max_length=16)),
                ('source', models.CharField(choices=[('legacy_imported', 'Legacy Imported'), ('ai_suggested', 'AI Suggested'), ('human_confirmed', 'Human Confirmed'), ('human_rejected', 'Human Rejected')], default='ai_suggested', max_length=24)),
                ('score', models.FloatField(blank=True, null=True)),
                ('predicted', models.BooleanField(default=False)),
                ('llm_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competing_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchings_as_competing_offer', to='core.offer')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchings', to='core.offer')),
            ],
            options={
                'indexes': [models.Index(fields=['competing_offer'], name='core_matchi_competi_2d4884_idx'), models.Index(fields=['status'], name='core_matchi_status_e85a7a_idx')],
                'constraints': [models.UniqueConstraint(fields=('offer', 'competing_offer'), name='uniq_matching_offer_competing')],
            },
        ),
        migrations.CreateModel(
            name='PriceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('price_cents', models.IntegerField()),
                ('list_price_cents', models.IntegerField(blank=True, null=True)),
                ('shipping_charges_cents', models.IntegerField(blank=True, null=True)),
                ('price_currency', models.CharField(default='EUR', max_length=3)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_observations', to='core.offer')),
            ],
            options={
                'indexes': [models.Index(fields=['offer', '-observed_at'], name='price_obs_offer_recent_idx')],
            },
        ),
        migrations.CreateModel(
            name='MainCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranked_in_main_competitions', to='core.retailer')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_competitions', to='core.retailer')),
            ],
            options={
                'ordering': ['retailer_id', 'position'],
                'constraints': [models.UniqueConstraint(fields=('retailer', 'position'), name='uniq_main_comp_retailer_position'), models.UniqueConstraint(fields=('retailer', 'competitor'), name='uniq_main_comp_retailer_competitor')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_as_competitor', to='core.retailer')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.offer')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.retailer')),
            ],
            options={
                'indexes': [models.Index(fields=['offer', 'retailer'], name='review_offer_retailer_idx')],
                'constraints': [models.UniqueConstraint(fields=('offer', 'retailer', 'competitor'), name='uniq_review_offer_ret_comp')],
            },
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['retailer', 'public'], name='core_offer_retaile_3c9d70_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['channel'], name='core_offer_channel_b09b09_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='offer_embedding_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.UniqueConstraint(fields=('website', 'sku', 'public'), name='uniq_offer_website_sku_public'),
        ),
    ]
