# Generated by Django 5.1.15 on 2026-04-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='common_sku',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='offer',
            name='ean',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='offer',
            name='sku',
            field=models.CharField(max_length=512),
        ),
    ]
