# Generated by Django 5.1.15 on 2026-04-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_offer_common_sku_alter_offer_ean_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='priceobservation',
            constraint=models.UniqueConstraint(fields=('offer', 'observed_at', 'price_cents'), name='unique_price_observation'),
        ),
    ]
